"""Add diccionario (data dictionary) table

Revision ID: 20260523_add_diccionario
Revises: 9a020001a476
Create Date: 2026-05-23 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260523_add_diccionario'
down_revision: Union[str, None] = '9a020001a476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diccionario',
    sa.Column('tabla', sa.String(length=100), nullable=False),
    sa.Column('columna', sa.String(length=100), nullable=False),
    sa.Column('tipo_dato', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('es_nulo', sa.Boolean(), nullable=False),
    sa.Column('es_llave_primaria', sa.Boolean(), nullable=False),
    sa.Column('es_llave_foranea', sa.Boolean(), nullable=False),
    sa.Column('llave_foranea_tabla', sa.String(length=100), nullable=True),
    sa.Column('llave_foranea_columna', sa.String(length=100), nullable=True),
    sa.Column('es_indice', sa.Boolean(), nullable=False),
    sa.Column('es_unico', sa.Boolean(), nullable=False),
    sa.Column('valor_por_defecto', sa.String(length=255), nullable=True),
    sa.Column('longitud_maxima', sa.Integer(), nullable=True),
    sa.Column('es_activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diccionario_columna'), 'diccionario', ['columna'], unique=False)
    op.create_index(op.f('ix_diccionario_tabla'), 'diccionario', ['tabla'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diccionario_tabla'), table_name='diccionario')
    op.drop_index(op.f('ix_diccionario_columna'), table_name='diccionario')
    op.drop_table('diccionario')
    # ### end Alembic commands ###
